<?php

/**
 * @file
 * Functionality for CKEditor Accordion.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function ckeditor_accordion_page_attachments_alter(array &$page) {
  $config = \Drupal::config('ckeditor_accordion.settings');

  // Attaches css assets globally.
  $page['#attached']['library'][] = 'ckeditor_accordion/accordion.frontend';

  // Pass settings to JavaScript.
  $page['#attached']['drupalSettings']['ckeditorAccordion']['accordionStyle'] = [
    'collapseAll' => $config->get('collapse_all'),
    'keepRowsOpen' => $config->get('keep_rows_open'),
    'animateAccordionOpenAndClose' => $config->get('animate_accordion_toggle') ?? 1,
    'openTabsWithHash' => $config->get('open_tabs_with_hash') ?? 1,
  ];
}
