<?php

/**
 * @file
 * Uses the PHPMailer library to send emails via SMTP.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function phpmailer_smtp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.phpmailer_smtp':
      $text = file_get_contents(__DIR__ . '/README.md');
      return '<pre>' . Html::escape($text) . '</pre>';

    default:
  }
}

/**
 * Implements hook_theme().
 */
function phpmailer_smtp_theme() {
  return [
    'phpmailer_smtp' => [
      'variables' => [
        'module' => '',
        'key' => '',
        'recipient' => '',
        'subject' => '',
        'body' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_phpmailer_smtp(array &$variables) {
  $variables['module'] = str_replace('_', '-', $variables['module']);
  $variables['key'] = str_replace('_', '-', $variables['key']);
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function phpmailer_smtp_theme_suggestions_phpmailer_smtp(array $variables) {
  return [
    'phpmailer_smtp__' . $variables['module'],
    'phpmailer_smtp__' . $variables['module'] . '__' . $variables['key'],
  ];
}
